extends Node

signal player_action_first
signal player_action_second

signal object_completed
signal game_won
signal game_lost
signal scoring_completed

signal switch_to_title
signal switch_to_level_selection
signal switch_to_level

signal do_the_actual_transition
